### ISSUE TITLE
Deprecated: Array and string offset access syntax with curly braces is deprecated in /www/wwwroot/cloud/core/class/dzz/dzz_database.php on line 302

### ISSUE THREAD

**Issue by Super-Gil** [zyx0814/dzzoffice#131]
有很多deprecated的方法用了 我这个无法正常使用了，详细见图
![WeChat Screenshot_20200524113822](https://user-images.githubusercontent.com/41502813/82745129-4759dd80-9db3-11ea-8fdf-8c9e1ee01ba6.png)

**Comment by hbliyafei** [comment]
我是修改出错文件行,将大括号替换为中括号解决的
$sql{$i} - 》 $sql[$i]
