### ISSUE TITLE
本地安装 网盘有设置的吗，上传按钮怎么 没有

### ISSUE THREAD

**Issue by guanhui07** [zyx0814/dzzoffice#14]
如题，https://a.photo/image/2mKH

**Comment by lijiangwei** [comment]
点我的网盘有上传按钮吗？
不同的用户怎么编辑同一个文档你知道吗？

**Comment by lijiangwei** [comment]
本地部署的你可以打开docx文档吗？

**Comment by zyx0814** [comment]
如果你的php版本为5.6，需要设置php.ini    set 'always_populate_raw_post_data' to '-1'

**Comment by zyx0814** [comment]
配置好 安装并配置好collabora online或office online这两个应用后，多个用户在网盘通过这两个应用打开同一个office文件就会自动进入协同模式

**Comment by guanhui07** [comment]
http://php.net/manual/zh/migration56.deprecated.php   应该使用php://input这个比较好吧，$HTTP_RAW_POST_DATA 不是要废弃了吗

**Comment by guanhui07** [comment]
https://a.photo/image/2kq1  php5.6.33 always_populate_raw_post_data 设置为On 清除模板缓存后，还是没上传按钮，是不支持5.6版本吗

**Comment by guanhui07** [comment]
开启了重启php，清除模板缓存 会报错 如上图 ，测试body体 已经是可以获取到的
`-> curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "aaa" http://localhost/test.php
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
string(3) "aaa"
`
