### ISSUE TITLE
请问这个项目还在维护吗

### ISSUE THREAD

**Issue by xvzhenduo** [zyx0814/dzzoffice#216]
上次release还在2020，请问这个项目还在维护吗

**Comment by yww0926** [comment]
release虽然是2020，但最近一两个月还是有代码更新的

**Comment by xvzhenduo** [comment]
我没说清楚，我的意思是这个项目目前是只进行漏洞修复而不增加新功能了吗

**Comment by yww0926** [comment]
这方面不太了解，可以去官网咨询一下作者本人。我看最近官网挂出了社区版和商业版的功能对比了，貌似工作重心都在商业定制版上
