### ISSUE TITLE
关于项目根路径URL的问题

### ISSUE THREAD

**Issue by yangbinmao** [zyx0814/dzzoffice#220]
提出问题：dzz启动后，如果你是用的ip+port访问项目，进入项目后，项目的后续所有请求的起点，都是这个ip。同理，如果使用的域名访问，项目中请求的头部就是域名的格式。那么这就会有个问题，比如，我在内网部署了项目，现在我想用外网访问，但是用外网和内网中间是用的nginx转发。nginx转发的地址是ip+port。最后就会出现问题，就是外网访问到项目，通过nginx转发后，项目的所有接口请求经过nginx转发后，又变成了ip，这就导致了，在外网访问ip，这肯定就访问不通的。
提出想法：是否可以把这个访问的路径以urlconfig的形式暴露出来。让我们可以选择的去修改，默认状态就是你可以还是保持项目原始样子（用什么访问，就以什么开头去请求后续借口），如果有需求，就可以把这个baseurl让我们固定成指定的url。比如这里我的需求就是固定成我外网的url。谢谢

问题二：关于修改为固定ip的 我是不是可以在update.php的第一次出现$_G['siteurl']的时候：$_G['siteurl'] = preg_replace('/\/install\/$/i', '/', $_G['siteurl']);
把这个修改为
$_G['siteurl']=我的域名      的方式   然后在执行项目的安装。就可以解决我的问题，我测试了好像不行。在线请问各位大佬，给我指导一下。

**Comment by zhujingling** [comment]
老哥，这个问题解决了嘛？

**Comment by yangbinmao** [comment]
一直没有解决，唉。
