### ISSUE TITLE
docker安装后 默认图标缺失

### ISSUE THREAD

**Issue by xuzheliang135** [zyx0814/dzzoffice#224]
![image](https://user-images.githubusercontent.com/37364772/198959313-2f5bdcf4-7482-4ce6-9a0b-42f6104745af.png)
管理界面icon图标缺失，只有新安装的插件才会有正常图标显示

**Comment by lijiekang** [comment]
我也试过了，docker安装如果制定了volume挂载，就会缺失图标，取消挂载就可以了

**Comment by ProgrammerVsita** [comment]
请问你这边部署好之后是怎么进去这个界面的，我使用 k8s 方式部署，页面只有：Welcome to my server!

**Comment by xuzheliang135** [comment]
> 请问你这边部署好之后是怎么进去这个界面的，我使用 k8s 方式部署，页面只有：Welcome to my server!
去其他issue看看吧，我用的是docker，没试过K8S的流程，可能会有区别

**Comment by ProgrammerVsita** [comment]
> > 请问你这边部署好之后是怎么进去这个界面的，我使用 k8s 方式部署，页面只有：Welcome to my server!
> > 去其他issue看看吧，我用的是docker，没试过K8S的流程，可能会有区别

应该没什么区别，我就是根据他们那个 docker-compose 改的 yaml 文件，请问你打开的 url 是 ip:port 吗，port 用的是哪个服务的端口，后面还有加什么别的接口吗

**Comment by xuzheliang135** [comment]
> > > 请问你这边部署好之后是怎么进去这个界面的，我使用 k8s 方式部署，页面只有：Welcome to my server!
> > > 去其他issue看看吧，我用的是docker，没试过K8S的流程，可能会有区别
> 
> 应该没什么区别，我就是根据他们那个 docker-compose 改的 yaml 文件，请问你打开的 url 是 ip:port 吗，port 用的是哪个服务的端口，后面还有加什么别的接口吗

端口自己在docker-compose的配置中看，有多个就挨个试过去，地址，端口对了，就能够访问，默认我记得不是80端口，你访问80可能就是问题原因
