### ISSUE TITLE
新建用户之后一直停留在登陆界面

### ISSUE THREAD

**Issue by sambodhi-cn** [zyx0814/dzzoffice#24]
用新建账户登陆，登陆之后还是停留在登陆界面，不知道哪里出问题了

**Comment by zyx0814** [comment]
因为你现在没有安装普通用户可用的应用，默认就会进入到管理员登陆界面，你到应用市场里面安装完应用，并且启用应用后，其他普通用户就不会默认进到管理应用里了
安装完应用后，到系统设置里面 设置 默认首页
