### ISSUE TITLE
dzz+onlyoffice 文档修改者信息有误

### ISSUE THREAD

**Issue by n3uz** [zyx0814/dzzoffice#36]
使用其他用户修改文档后，文件动态中显示的修改者仍然是上传者。
如图最后两次修改使用了两个不同的用户，但动态信息显示仍然是上传者的，不知道是不是一个问题
![qq 20180508091905](https://user-images.githubusercontent.com/11814103/39732595-e9cdb506-52a0-11e8-80df-1c7d5e840a78.png)

dzzoffice2.0
onlyoffice2.0 
documentserver ：dockerhub onlyoffice/documentserver

**Comment by zyx0814** [comment]
新版已修复
