### ISSUE TITLE
社区版 V2.01，应用升级，一键升级后，会无限循环这个升级，且版本已经是最新版本了，还会提示升级

### ISSUE THREAD

**Issue by hyperwd** [zyx0814/dzzoffice#41]
![gcs96ee _uxjh t _s 5](https://user-images.githubusercontent.com/5171317/40789644-7f8d87b0-6525-11e8-92b5-19eb6c047153.png)
![90wu 5iabl2v ocq9_7b ok](https://user-images.githubusercontent.com/5171317/40789652-83c5a970-6525-11e8-9cfd-116fd1763e3f.jpg)

**Comment by zyx0814** [comment]
这个是我们的应用市场服务器问题，已修复
