### ISSUE TITLE
云盘: 文件夹下有子文件存在且文件大小大于0B，但是文件夹大小显示为0B，应该为子文件之和

### ISSUE THREAD

**Issue by zzhtom** [zyx0814/dzzoffice#47]
如下图所示：
![image](https://user-images.githubusercontent.com/19570807/41845542-6a17a318-78a6-11e8-9acf-9b08ee8ff939.png)

**Comment by zyx0814** [comment]
文件夹支持点击选中，右侧面板查看大小等信息，在列表中不会显示大小（和windows系统类似，显示的话系统消耗会增加很多）
