### ISSUE TITLE
网盘上传不了大于 2.5Mb 的文件

### ISSUE THREAD

**Issue by kuleyu** [zyx0814/dzzoffice#62]
网盘上传不了大于 2.5Mb 的文件，提示"**the uploaded file exceeds the upload_max_filesize directive in php.ini**"。
![image](https://user-images.githubusercontent.com/25771340/44579704-d5152d00-a7c9-11e8-9741-dda31aa74b7b.png)

在 "**系统设置---空间设置**"的参数都清除了还是不行。请问要怎么解决?
![image](https://user-images.githubusercontent.com/25771340/44579663-ab5c0600-a7c9-11e8-905b-fcb90d845221.png)

**Comment by kuleyu** [comment]
我试着改了一下这个文件 `dzzoffice/config/config.php` 的配置，如下
```
// --------------------------  CONFIG SERVER  --------------------------- //
$_config['server']['id'] = 1;
$_config['server']['client_max_body_size'] = '5G';           // 新增
$_config['server']['client_body_buffer_size'] = '5120K';    //新增
```
可还是不行。我是个php小白，是不是理解错了？所以@coffee0818 您能说得具体一些吗（是哪个文件、要怎么改）？

**Comment by coffee0818** [comment]
不是程序本身改，是修改网站的配置文件，nginx/conf 下面对应的该站点配置文件。

**Comment by kuleyu** [comment]
虽然用的不是 nginx, 但是还是根据您给的大致思路找到了解决方法，感谢！🤝🙏
![image](https://user-images.githubusercontent.com/25771340/44629898-68945c80-a988-11e8-9401-529e8637229b.png)

**Comment by v587xpt** [comment]
> 在conf的server{}里面显式指定： client_max_body_size 4G; =>4G修改为你想要限制的大小 client_body_buffer_size 2048K; =>2048K可以修改为更小或更大

感谢，在nginx里修改了这个参数，可以上传大文件了
