### ISSUE TITLE
何时才有微软的office接口安装教程呢~~

### ISSUE THREAD

**Issue by Mabisi** [zyx0814/dzzoffice#7]
何时才有微软的office接口安装教程呢~~

**Comment by saygoodbyebye** [comment]
@fhxsnabi   非常期待~~

**Comment by zyx0814** [comment]
officeOnline应用 http://www.dzzoffice.com/index.php?mod=dzzmarket&op=view&mid=32

**Comment by saygoodbyebye** [comment]
@zyx0814 赞！！
