### ISSUE TITLE
文件存储在对象存储上，走服务器带宽还是对象存储的带宽呢？

### ISSUE THREAD

**Issue by Woooosz** [zyx0814/dzzoffice#98]
我的服务器小水管，但是在预览某些pdf的时候希望放到对象存储上，请问对象存储的流量走的是服务器带宽还是对象存储的流量呢？

**Comment by jymusic0663** [comment]
可以看官方这个文档流程图
http://dzz.cc/corpus/list?cid=1#fid_30

![](http://lebook.me/index.php?mod=io&op=thumbnail&width=0&height=0&original=1&path=MDQxNldCVWJQclJBci9aZ2hwaTRxazdjYWt2U3lLN3VDZVZ4R1QzSWpPZFpSdFI4b1NxanE2WjFnQQ==)

**Comment by Woooosz** [comment]
@jymusic0663 谢谢！
